version: "3.7"

services:
  app-compliancelite:
    build:
      context: ./
      dockerfile: release.Dockerfile
    container_name: app-compliancelite
    restart: always
    env_file:
      - app/dev.env
    volumes:
      - "./app:/app"
    ports:
      - "8080:8080"
